### PR TITLE
Added elevator UI and logic.

### PR DESCRIPTION
**Pull request by 667bdrm**
Added type and level properties to ElevatorSceneryObject
Added elevator buttons to ImageButtonFactory
Added loading custom map loading to StateLocationHelper
Added elevator types loading from data/elevators.txt (from Anchorite@Teamx doc)
Added ElevatorProgress UI widget
Added ElevatorDialog state
Added metarule(15, x) opcode handler logic, Elevator Stub locating logic
Added basic elevator logic

Maps used for testing: vctyvlt, depolvb, vault13, redwame, mbase12, mbase34, depolva

[Demo](https://imgur.com/GV8k2ZN)

### CODE REVIEW

**Comment by alexeevdv** [comment]
Could you please resolve conflicts?

**Comment by 667bdrm** [comment]
Done, but looks like AppVeyor does not built it. The conflict was only in changelog. Maybe it should succeed in next scheduled build.

**Comment by 667bdrm** [comment]
Done

**Comment by alexeevdv** [comment]
Thanks

**Pull request merged**
