### PR TITLE
Timers (concept)

### PR DESCRIPTION
**Pull request by phobos2077**
#418 
Just an example implementation of Timers. There are 2 classes for timers - "Timer" works in real-time (milliseconds) and "GameTimer" in game ticks (which advance only during "real-time" portion of the game). They share the same base class.

Used in 2 places:
* Cursor dropdown, when pressing and holding mouse.
* VM-scripted game timers, added with *add_timer_event* (this can be observed by rats moving about on "klamall" map, for example).

### CODE REVIEW

**Comment by isage** [comment]
Could you up generic timer resolution to nanoseconds?
( for example using https://github.com/falltergeist/falltergeist/blob/master/src/UI/MvePlayer.cpp#L912 )
Or add HiResTimer class.

**Comment by phobos2077** [comment]
I think for general purpose timers there is no point in nanosecond resolution, because in our main loop we have this: 
`SDL_Delay(1);`
Which basically limits FPS to 1000 (if I understand correctly). And since all processing is tied to main loop, nanosecond resolution could only be useful in some vary specific places (can't even think of any, do you?).

**Comment by isage** [comment]
Movies)
Also, SDL_Delay kinda fluctuates.

**Comment by phobos2077** [comment]
I'm not familiar with clock_gettime function. It is not in standard? Also I think if you are dealing with nanoseconds, Timers might be too slow for you because they use Delegate which use std::function - several levels of indirection. Milliseconds-timer is aimed for UI stuff (scrolling, long presses, animations) and basically everything that works inside main loop. Ticks-timer is currently used for "add_timer_event", and other possible use is timed explosives.

**Pull request merged**
