### PR TITLE
Fix linking release builds on Windows

### PR DESCRIPTION
**Pull request by JanSimek**

### CODE REVIEW

**Comment by JanSimek** [comment]
- fixed linking Release, RelWithDebInfo and MinSizeRel builds
- prevent immediate closing of console window after a crash, so the user has a chance to see what's wrong
- group source files into Headers and Sources in Visual Studio. QtCreator does this automatically and I don't know about other IDEs, so I only enabled it for MSVC

msvc-tree

**Comment by alexeevdv** [comment]
Can you please also update changelog?

**Comment by JanSimek** [comment]
Done

**Comment by alexeevdv** [comment]
Thanks!

**Pull request merged**
