### PR TITLE
Update Readme and add Linux Desktop support

### PR DESCRIPTION
**Pull request by shsorbom**
The readme was missing the zlib dependency and information on global installs.
Installation of a .desktop file is necessary in Linux for Falltergiest to show up in desktop menus.
I did not include the bundled icon because it is the wrong size and filename. I did not wish to tamper with it in case there was a reason for this.

### CODE REVIEW

**Comment by isage** [comment]
1) we are not currently accepting packaging pull-requests. Because we are in early alpha WIP stage and it doesn't make sense. However, as it's relatively small and trivial, i'm okay with making exception this time.
2) "Remake of Fallout 2" - it's not a remake. It's opensource engine for it.
3) >zlib1g - a think we should remove distro-specific package names from readme, or create distro-specific sections.

**Comment by isage** [comment]
Also, ignore Travis-CI failure. Looks like we need to find another source of fresh clang packages, meh.

**Comment by isage** [comment]
Also, there's no reason for icon filename/size/etc. It's just a placeholder for now.

**Comment by shsorbom** [comment]
How does adding new commits for a pull request work? do I nee to file another one to fix the comment issue?

**Comment by isage** [comment]
Just add commit to the same branch

**Comment by shsorbom** [comment]
Done.

**Pull request merged**
