### PR TITLE
Libfalltergeist includes changed

### PR DESCRIPTION
**Pull request by alexeevdv**

### CODE REVIEW

**Comment by phobos2077** [comment]
This cmake changes give me a lot of errors:

```
Error:Configuration Debug
file COPY cannot copy file "C:/Projects/falltergeist/lib/libfalltergeist/src/Ini/Value.h" to "C:/Projects/falltergeist/lib/libfalltergeist/include//src/Ini/Value.h".

Error:Configuration Debug
file RENAME failed to rename
  C:/Projects/falltergeist/lib/libfalltergeist/include/src
to
  C:/Projects/falltergeist/lib/libfalltergeist/include/libfalltergeist
because: No such file or directory

Error:Configuration Release
file COPY cannot set permissions on "C:/Projects/falltergeist/lib/libfalltergeist/include//src"

```

Each time I run cmake, it shows different errors (different file names).

**Comment by alexeevdv** [comment]
Looks like there is one redundant slash in CMakeLists.txt

**Comment by alexeevdv** [comment]
Try again. This should solve the issue

**Comment by phobos2077** [comment]
Still the same problems:
```
Error:Configuration Debug
file COPY cannot set modification time on "C:/Projects/falltergeist/lib/libfalltergeist/include/src/Fon/Glyph.h"

Error:Configuration RelWithDebInfo
file COPY cannot set modification time on "C:/Projects/falltergeist/lib/libfalltergeist/include/src/Map/File.h"

Error:Configuration RelWithDebInfo
file RENAME failed to rename
  C:/Projects/falltergeist/lib/libfalltergeist/include/src
to
  C:/Projects/falltergeist/lib/libfalltergeist/include/libfalltergeist
because: No such file or directory

Error:Configuration MinSizeRel
file COPY cannot set permissions on "C:/Projects/falltergeist/lib/libfalltergeist/include/src/Fon/Glyph.h"

```

**Comment by alexeevdv** [comment]
I tested this in Windows XP using Netbeans + CMake + MingGW + MSys

No problems at all

**Comment by phobos2077** [comment]
CLion. I know it's not polished, but much more comfortable than NetBeans :)

**Pull request merged**
