### PR TITLE
Talking heads

### PR DESCRIPTION
**Pull request by isage**
Ugh. Sorry it took so long.
So:
1) I've fixed critter age and gender, so now dialogues are "gendered".
2) Get/Set music volume. Ability to restart last played track.
3) Speech playing. 
4) Fully working talking heads. With fidgets, lipsync and transitions.
5) Implemented Dialog Review.
6) Added "monitor window" corner highlights. Note new files in data/.
7) Fixed some minor non-standard compliant code. This should help a little with implementing VisualStudio build in the future.
8) Implemented critter->scrName(). It's bassicaly a name of attached to critter script, according to scrname.msg. This is used in Dialog review, and, maybe, some other places.

### CODE REVIEW

**Comment by alexeevdv** [comment]
Dude... this is f***ing awesome! Talking heads.....can't believe my eyes :) Thanks

**Comment by phobos2077** [comment]
You're a real hero, iSage. Looks like the most complicated stuff is done and this project future looks bright.

**Comment by JanSimek** [comment]
Wasn't this merged three months ago?

**Comment by phobos2077** [comment]
I just found out about it :)

**Pull request merged**
