### PR TITLE
Use two worker threads to build code on travis

### PR DESCRIPTION
**Pull request by janisozaur**
Travis-CI offers up to 2 cores on worker nodes[1], make use of both of them.

[1] https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments

### CODE REVIEW

**Comment by janisozaur** [comment]
|               | -j1 (before this change) | -j2     |
|---------------|--------------------------|---------|
| Total time    | 12m 3s                   | 20m 13s |
| Linux + clang | 5m 3s                    | 4m 42s  |
| Linux + gcc   | 3m 31s                   | 5m 9s   |
| OS X + clang  | 8m 54s                   | 5m 32s  |
| OS X + gcc    | 9m 24s                   | 5m 50s  |
| Wall clock    | 12m 3s                   | 7m 58s  |

**Comment by phobos2077** [comment]
So it actually got slower overall? What's the point?

**Comment by janisozaur** [comment]
Oh, no. I copied the wrong value in the first row, sorry. The table is now updated.

**Comment by janisozaur** [comment]
Do note the single outlier `Linux + gcc` is likely due to this build configuration crashing. It set to be fixed in https://github.com/falltergeist/falltergeist/pull/497

**Pull request merged**
